trigger:
- main

pool:
  name: Hitesh_Offie_PC_Pool

steps:

- task: TerraformInstaller@1
  displayName: 'terraform install'
  inputs:
    terraformVersion: 'latest'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      ls
      pwd


- task: TerraformTask@5
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent_module'
    backendServiceArm: 'YAML Service Connection'
    backendAzureRmStorageAccountName: 'punitstg'
    backendAzureRmContainerName: 'punitcontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: 'terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent_module'
    environmentServiceNameAzureRM: 'YAML Service Connection'

- task: TerraformTask@5
  displayName: 'terraform apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent_module'
    environmentServiceNameAzureRM: 'YAML Service Connection'







